# Generated by Django 3.2.7 on 2021-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='id',
        ),
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='شماره VIN خودرو'),
        ),
    ]
