# Generated by Django 3.2.7 on 2021-10-08 10:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211005_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='sahebcar',
        ),
        migrations.AddField(
            model_name='cars',
            name='sahebcodemeli',
            field=models.IntegerField(default=0, verbose_name='نام صاحب ماشین'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='gearbox',
            field=models.BooleanField(default=0, verbose_name='2جعبه دنده '),
        ),
        migrations.AlterField(
            model_name='cars',
            name='gearbox2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dandei', 'دنده ای'), ('automatic', 'اتوماتیک')], max_length=16, verbose_name='جعبه دنده '),
        ),
    ]
