# Generated by Django 3.2.7 on 2021-12-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_cars_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='updated_at',
        ),
    ]
