# Generated by Django 3.2.7 on 2022-02-27 19:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20211208_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='shasinumber',
        ),
        migrations.AddField(
            model_name='cars',
            name='sazande',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dandei', 'دنده ای'), ('automatic', 'اتوماتیک')], default=1, max_length=16, verbose_name='سازنده '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='typebadane',
            field=models.CharField(default=2, max_length=20, verbose_name='نوع بدنه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='modelcar',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('dandei', 'دنده ای'), ('automatic', 'اتوماتیک')], max_length=16, verbose_name='مدل ماشین'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='pelak',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sahebcodemeli',
            field=models.IntegerField(verbose_name='کد ملی صاحب ماشین'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vin',
            field=models.CharField(max_length=20, verbose_name='شماره VIN خودرو'),
        ),
    ]
