# Generated by Django 3.2.7 on 2022-03-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0007_auto_20220227_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='emkanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabt', models.BooleanField(default=0, verbose_name='ضبط صوتی')),
            ],
        ),
        migrations.CreateModel(
            name='sazande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام سازنده')),
            ],
            options={
                'verbose_name': 'سازنده',
                'verbose_name_plural': 'سازنده ها',
            },
        ),
        migrations.RemoveField(
            model_name='cars',
            name='gearbox2',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='priceperday',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='sahebcodemeli',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='saltolid',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='tozihat',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='typebadane',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='vin',
        ),
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='karkard',
            field=models.CharField(default=50, max_length=20, verbose_name='کارکرد'),
        ),
        migrations.CreateModel(
            name='modelcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام مدل')),
                ('saltolid', models.DateField(default=1, verbose_name='سال تولید')),
                ('typebadane', models.CharField(max_length=20, verbose_name='نوع بدنه')),
                ('gearbox2', multiselectfield.db.fields.MultiSelectField(choices=[('dandei', 'دنده ای'), ('automatic', 'اتوماتیک')], max_length=16, verbose_name='جعبه دنده ')),
                ('sazande', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='cars.sazande', verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'مدل ماشین',
                'verbose_name_plural': 'مدل های ماشین',
            },
        ),
        migrations.CreateModel(
            name='ghavanin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tozihat', models.TextField(verbose_name='توضیحات')),
                ('driver_status', multiselectfield.db.fields.MultiSelectField(choices=[('with_driver', 'با راننده'), ('without_driver', 'بدون راننده'), ('both', 'با راننده و بدون راننده هر دو امکان پذیر است')], max_length=31, verbose_name='با راننده یا بدون راننده؟')),
                ('mahdoodiatperhour', models.IntegerField(verbose_name='هزینه اضافه به ازای هر ساعت')),
                ('mahdoodiatperkm', models.IntegerField(verbose_name='محدودیت کیلومتری')),
                ('priceperkm', models.IntegerField(verbose_name='هزینه اضافه به ازای هر کیلومتر')),
                ('zemanat', models.TextField(verbose_name='ضمانت')),
                ('kamtarin_rooz_ejare', models.IntegerField(verbose_name='حداقل مدت اجاره')),
                ('nahve_tahvil', multiselectfield.db.fields.MultiSelectField(choices=[('dandei', 'دریافت در محل'), ('automatic', 'تحویل ماشین')], max_length=16)),
                ('priceperday', models.IntegerField(verbose_name='قیمت اجاره روزانه به تومان')),
                ('cars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.cars', verbose_name='ماشین')),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='modelcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelcar', to='cars.modelcar'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sazande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sazande', to='cars.sazande'),
        ),
    ]
